export const data = [
  {
    name: "MD5",
    hashcat: 0,
    john: "raw-md5",
    extended: false,
    description: "Used for Linux Shadow files.",
  },
  {
    name: "MD4",
    hashcat: 900,
    john: "raw-md4",
    extended: false,
    description: null,
  },
  {
    name: "Double MD5",
    hashcat: 2600,
    john: null,
    extended: false,
    description: null,
  },
  { name: "LM", hashcat: 3000, john: "lm", extended: false, description: null },
  {
    name: "RIPEMD-128",
    hashcat: null,
    john: "ripemd-128",
    extended: false,
    description: null,
  },
  {
    name: "Haval-128",
    hashcat: null,
    john: "haval-128-4",
    extended: false,
    description: null,
  },
  {
    name: "Tiger-128",
    hashcat: null,
    john: null,
    extended: false,
    description: null,
  },
  {
    name: "Skein-256(128)",
    hashcat: null,
    john: null,
    extended: false,
    description: null,
  },
  {
    name: "Skein-512(128)",
    hashcat: null,
    john: null,
    extended: false,
    description: null,
  },
  {
    name: "Lotus Notes/Domino 5",
    hashcat: 8600,
    john: "lotus5",
    extended: false,
    description: null,
  },
  {
    name: "Skype",
    hashcat: 23,
    john: null,
    extended: false,
    description: null,
  },
  {
    name: "ZipMonster",
    hashcat: null,
    john: null,
    extended: true,
    description: null,
  },
  {
    name: "PrestaShop",
    hashcat: 11000,
    john: null,
    extended: true,
    description: null,
  },
  {
    name: "md5(md5(md5($pass)))",
    hashcat: 3500,
    john: null,
    extended: true,
    description: null,
  },
  {
    name: "md5(strtoupper(md5($pass)))",
    hashcat: 4300,
    john: null,
    extended: true,
    description: null,
  },
  {
    name: "md5(sha1($pass))",
    hashcat: 4400,
    john: null,
    extended: true,
    description: null,
  },
  {
    name: "md5($pass.$salt)",
    hashcat: 10,
    john: null,
    extended: true,
    description: null,
  },
  {
    name: "md5($salt.$pass)",
    hashcat: 20,
    john: null,
    extended: true,
    description: null,
  },
  {
    name: "md5(unicode($pass).$salt)",
    hashcat: 30,
    john: null,
    extended: true,
    description: null,
  },
  {
    name: "md5($salt.unicode($pass))",
    hashcat: 40,
    john: null,
    extended: true,
    description: null,
  },
  {
    name: "HMAC-MD5 (key = $pass)",
    hashcat: 50,
    john: "hmac-md5",
    extended: true,
    description: null,
  },
  {
    name: "HMAC-MD5 (key = $salt)",
    hashcat: 60,
    john: "hmac-md5",
    extended: true,
    description: null,
  },
  {
    name: "md5(md5($salt).$pass)",
    hashcat: 3610,
    john: null,
    extended: true,
    description: null,
  },
  {
    name: "md5($salt.md5($pass))",
    hashcat: 3710,
    john: null,
    extended: true,
    description: null,
  },
  {
    name: "md5($pass.md5($salt))",
    hashcat: 3720,
    john: null,
    extended: true,
    description: null,
  },
  {
    name: "md5($salt.$pass.$salt)",
    hashcat: 3810,
    john: null,
    extended: true,
    description: null,
  },
  {
    name: "md5(md5($pass).md5($salt))",
    hashcat: 3910,
    john: null,
    extended: true,
    description: null,
  },
  {
    name: "md5($salt.md5($salt.$pass))",
    hashcat: 4010,
    john: null,
    extended: true,
    description: null,
  },
  {
    name: "md5($salt.md5($pass.$salt))",
    hashcat: 4110,
    john: null,
    extended: true,
    description: null,
  },
  {
    name: "md5($username.0.$pass)",
    hashcat: 4210,
    john: null,
    extended: true,
    description: null,
  },
  {
    name: "WebEdition CMS",
    hashcat: 3721,
    john: null,
    extended: false,
    description: null,
  },
  {
    name: "Joomla < v2.5.18",
    hashcat: 11,
    john: null,
    extended: false,
    description: null,
  },
  {
    name: "SAM(LM_Hash:NT_Hash)",
    hashcat: null,
    john: null,
    extended: false,
    description: null,
  },
  {
    name: "MD5(Chap)",
    hashcat: 4800,
    john: "chap",
    extended: false,
    description: null,
  },
  {
    name: "iSCSI CHAP Authentication",
    hashcat: 4800,
    john: "chap",
    extended: false,
    description: null,
  },
];
